// <auto-generated />
namespace TauTau.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20190103 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20190103));
        
        string IMigrationMetadata.Id
        {
            get { return "201901022136321_20190103"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
